2024-12-20 13:27:30,832 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\kosti\PycharmProjects\pythonProject\UrbanUniversity\tests_12\tests_12_4.py", line 72, in test_run
    runner = Runner(12345)
  File "C:\Users\kosti\PycharmProjects\pythonProject\UrbanUniversity\tests_12\tests_12_4.py", line 13, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-12-20 13:27:30,833 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\kosti\PycharmProjects\pythonProject\UrbanUniversity\tests_12\tests_12_4.py", line 60, in test_walk
    runner = Runner("Test Runner Walk", -5)
  File "C:\Users\kosti\PycharmProjects\pythonProject\UrbanUniversity\tests_12\tests_12_4.py", line 18, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
